### ISSUE TITLE
"Wire." replace to "_wire->"

### ISSUE THREAD

**Issue by arcsin** [RobTillaart/DS3232#5]
Hello! Excuse me. I am not expert in programming. I use your lib, and my DS3231 on I2C2 (Wire1).  
for example 
```
68 :   if (Wire.requestFrom(_address, (uint8_t)7) != 7)     -- not working
  if (_wire->requestFrom(_address, (uint8_t)7) != 7)    -- working.
```
 in this file I found 4 place like that.
my board is ESP32-s3

**Comment by RobTillaart** [comment]
Thank you for catching this one, .
Will investigate it asap (currently in the mid of another major update :)

**Comment by RobTillaart** [comment]
(note to myself - did I check in the latest version)

**Comment by RobTillaart** [comment]
@arcsin 
BUG confirmed.
The bug was not found as I only tested with an UNO and not tested a different Wire (I2C) bus.

**Comment by RobTillaart** [comment]
> in this file I found 4 place like that.

actually there were 5 😒

**Comment by RobTillaart** [comment]
Created a develop branch and a PR

**Comment by RobTillaart** [comment]
@arcsin 
build is successful, will merge fix asap

**Comment by RobTillaart** [comment]
Merge is running,

> my board is ESP32-s3

If you find other issues with your ESP tests, please let me know
Again thanks for finding this bug

**Comment by arcsin** [comment]
Ok, thank you for speed)
